domain: william-leeson.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://william-leeson.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /privacy-policy/  
collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"